### ISSUE TITLE
Use Button on Carousel Build

### ISSUE THREAD

**Issue by muflihfq** [serenader2014/flutter_carousel_slider#123]
as mentioned in the doc, there are several instance methods, but it is possible to make it work also when you use build? or there is a way to work around it?

**Comment by serenader2014** [comment]
For the instance methods, there will be a breaking change in the next release, you can create your own `CarouselController`, and pass it to the `CarouselSlider`, so that you can use `carouselController. nextPage ` or other methods in anywhere.

This feature is already in the master branch, you can use it now. I'll publish it to the pub.dev in the next few days.

**Comment by muflihfq** [comment]
thank you, appreciate it

**Comment by serenader2014** [comment]
`v2.0.0` is published to the pub.dev, please give it a try!
