### ISSUE TITLE
Expose PageController

### ISSUE THREAD

**Issue by lsaudon** [serenader2014/flutter_carousel_slider#49]
It would be nice to be able to expose the PageController to avoid having the entire carousel to change the page.

**Comment by Teo03** [comment]
I have exposed the PageController by doing the following:

In _**carousel_slider.dart**_ (the package source) I added `var pageController` in the constructor and assigned it to `this.pageController = pageController` (instead of `this.pageController = PageController(.....);`)

After that in my **_main.dart_** I added this: 
`final PageController _pageController = PageController(
        viewportFraction: 0.8,
        initialPage: 0,
    );`,
and now you can set the `pageController` inside `CarouselSlider()` to this: `CarouselSlider(
            pageController: _pageController,
... )`

You can call `_pageController` anywhere in your code and control the slider for example: `_pageController.animateToPage()`
