### ISSUE TITLE
Request : disallow gesture option

### ISSUE THREAD

**Issue by QuentinSc** [serenader2014/flutter_carousel_slider#65]
Hello,

Little request from my side, a parameter to enable/disable the gesture for next/previous item.
I have a use case where I could juste authorize next/previous item by button.

Sorry for my english, I wish it was clear

Thank you very much !

**Comment by LeandroMoura3** [comment]
Hello.

A think that a workaround for it put a container transparent in on stack of the same size of the carousel. Or you case use a widget called AbsorbPointer: https://api.flutter.dev/flutter/widgets/AbsorbPointer-class.html

**Comment by QuentinSc** [comment]
Thanks for the tip. Unfortunately I don't want to block the slider's children :(

**Comment by joelbrostrom** [comment]
Hi!
With the latest version 1.3.1 there is a new constructor argument called 'scrollPhysics'.
Try setting it to 'NeverScrollableScrollPhysics()'.  

Hopefully it will disable gesture scroll but still work with calling the next/previous methods.  

Please tell us if it work so that we can close the issue.

**Comment by QuentinSc** [comment]
Hi !
1.3.1 is the perfect version, it works :)
Thank you very much !
