### ISSUE TITLE
IntegerDivisionByZeroException was thrown building

### ISSUE THREAD

**Issue by BugsBunnyBR** [serenader2014/flutter_carousel_slider#70]
```

The following IntegerDivisionByZeroException was thrown building:
IntegerDivisionByZeroException

When the exception was thrown, this was the stack: 
#0      int.% (dart:core-patch/integers.dart:34:7)
#1      _remainder (package:carousel_slider/carousel_slider.dart:287:28)
#2      _getRealIndex (package:carousel_slider/carousel_slider.dart:281:10)
#3      _CarouselSliderState.build.<anonymous closure> (package:carousel_slider/carousel_slider.dart:231:13)

```

Is there any handling the library could do?

**Comment by joelbrostrom** [comment]
This is thrown when the length of your item set is == 0, i.e. when you are initiating the carousel without any items.

If we were to work around this error we would get an out of index error instead since we would try to build item `items[0]` or nullPointerExeption`items[null]` depending on our implementation.

What is it you are trying to do?

**Comment by BugsBunnyBR** [comment]
> This is thrown when the length of your item set is == 0, i.e. when you are initiating the carousel without any items.
> 
> If we were to work around this error we would get an out of index error instead since we would try to build item `items[0]` or nullPointerExeption`items[null]` depending on our implementation.
> 
> What is it you are trying to do?

I just received some images from the server, but the list way empty... I will start checking for null or empty before using the library.
Thanks.
